//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsData.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TablesData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TablesData() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PavilionsData.Resources.TablesData", typeof(TablesData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_City&quot;: 1,
        ///        &quot;CityName&quot;: &quot;Москва&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_City&quot;: 2,
        ///        &quot;CityName&quot;: &quot;Санкт-Петербург&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_City&quot;: 3,
        ///        &quot;CityName&quot;: &quot;Новосибирск&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_City&quot;: 4,
        ///        &quot;CityName&quot;: &quot;Екатеринбург&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_City&quot;: 5,
        ///        &quot;CityName&quot;: &quot;Нижний Новгород&quot;,
        ///        &quot;RecordStatus&quot;: [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Id_Employee&quot;:1,&quot;Surname&quot;:&quot;\u0427\u0430\u0448\u0438\u043D&quot;,&quot;Name&quot;:&quot;\u0415\u043B\u0438\u0437\u0430\u0440&quot;,&quot;Middlename&quot;:&quot;\u041C\u0438\u0445\u0435\u0435\u0432\u0438\u0447&quot;,&quot;Login&quot;:&quot;Elizor@gmail.com&quot;,&quot;Password&quot;:&quot;XuS5gIyslrxC6avC/6rYua6iuwxBnN13sK\u002BPBj5UiTc=&quot;,&quot;Id_Role&quot;:4,&quot;PhoneNumber&quot;:&quot;71070628291&quot;,&quot;Photo&quot;:&quot;/9j/4AAQSkZJRgABAQEAYQBhAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gODUK/9sAQwAFAwQEBAMFBAQEBQUFBgcMCAcHBwcPCwsJDBEPEhIRDxERExYcFxMUGhURERghGBodHR8fHxMXIiQiHiQcHh8e/9 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_Pavilion&quot;: 1,
        ///        &quot;Id_PavilionsStatus&quot;: 2,
        ///        &quot;Id_ShoppingCenter&quot;: 1,
        ///        &quot;Number&quot;: &quot;88А&quot;,
        ///        &quot;Floor&quot;: 1,
        ///        &quot;Area&quot;: 75,
        ///        &quot;Price&quot;: 3307.7,
        ///        &quot;AddedValueCoefficient&quot;: 0.1,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Pavilion&quot;: 2,
        ///        &quot;Id_PavilionsStatus&quot;: 3,
        ///        &quot;Id_ShoppingCenter&quot;: 2,
        ///        &quot;Number&quot;: &quot;40А&quot;,
        ///        &quot;Floor&quot;: 3,
        ///        &quot;Area&quot;: 96,
        ///        &quot;Price&quot;: 690,
        ///        &quot;AddedValueCoefficient&quot;: 1.1,
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Pavilions {
            get {
                return ResourceManager.GetString("Pavilions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_PavilionsStatus&quot;: 1,
        ///        &quot;PavilionsStatusName&quot;: &quot;Удален&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_PavilionsStatus&quot;: 2,
        ///        &quot;PavilionsStatusName&quot;: &quot;Свободен&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_PavilionsStatus&quot;: 3,
        ///        &quot;PavilionsStatusName&quot;: &quot;Забронирован&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_PavilionsStatus&quot;: 4,
        ///        &quot;PavilionsStatusName&quot;: &quot;Арендован&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    }
        ///].
        /// </summary>
        internal static string PavilionsStatuses {
            get {
                return ResourceManager.GetString("PavilionsStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_Rental&quot;: 1,
        ///        &quot;Id_Tenant&quot;: 2,
        ///        &quot;Id_ShoppingCenter&quot;: 3,
        ///        &quot;Id_Pavilion&quot;: 1,
        ///        &quot;Id_Employee&quot;: 2,
        ///        &quot;Id_RentalStatus&quot;: 1,
        ///        &quot;StartDate&quot;: &quot;24.01.2019&quot;,
        ///        &quot;EndDate&quot;: &quot;17.11.2020&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Rental&quot;: 2,
        ///        &quot;Id_Tenant&quot;: 2,
        ///        &quot;Id_ShoppingCenter&quot;: 2,
        ///        &quot;Id_Pavilion&quot;: 2,
        ///        &quot;Id_Employee&quot;: 7,
        ///        &quot;Id_RentalStatus&quot;: 2,
        ///        &quot;StartDate&quot;: &quot;21.11.2019&quot;,
        ///        &quot;EndDat [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Rentals {
            get {
                return ResourceManager.GetString("Rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_RentalStatus&quot;: 1,
        ///        &quot;RentalStatusName&quot;: &quot;Открыт&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_RentalStatus&quot;: 2,
        ///        &quot;RentalStatusName&quot;: &quot;Ожидание&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_RentalStatus&quot;: 3,
        ///        &quot;RentalStatusName&quot;: &quot;Закрыт&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    }
        ///].
        /// </summary>
        internal static string RentalsStatuses {
            get {
                return ResourceManager.GetString("RentalsStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_Role&quot;: 1,
        ///        &quot;RoleName&quot;: &quot;Удален&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Role&quot;: 2,
        ///        &quot;RoleName&quot;: &quot;Менеджер А&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Role&quot;: 3,
        ///        &quot;RoleName&quot;: &quot;Менеджер С&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Role&quot;: 4,
        ///        &quot;RoleName&quot;: &quot;Администратор&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    }
        ///].
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Id_ShoppingCenter&quot;:1,&quot;Name&quot;:&quot;\u0420\u0438\u0432\u044C\u0435\u0440\u0430&quot;,&quot;Id_ShoppingCenterStatus&quot;:2,&quot;PavilionsCount&quot;:0,&quot;Id_City&quot;:1,&quot;Price&quot;:8260042,&quot;AddedValueCoefficient&quot;:0.5,&quot;FloorsNumber&quot;:4,&quot;Photo&quot;:&quot;/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxATEBIQExIPEhATDRAXExIXEBEeDhAeIBIXGxYRHx8kKCgsJCYxJxMVLTQtJzUtOi4uFx8zODMsNygtLisBCgoKDg0OFxAQGTcdHSY3LSsrNysrLy0tLSstKy0vNy0tLTMuNysvLTctLS0tLSstLy0rKy0tLS0tLS0rKy0tLf/AABEIAJYAyAMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAFAAIDBAYBB//EAEYQAAIBAwIDBAcFBAcGBwAAAAECAwAEERI [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ShoppingCenters {
            get {
                return ResourceManager.GetString("ShoppingCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_ShoppingStatus&quot;: 1,
        ///        &quot;ShoppingStatusName&quot;: &quot;Удален&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_ShoppingStatus&quot;: 2,
        ///        &quot;ShoppingStatusName&quot;: &quot;План&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_ShoppingStatus&quot;: 3,
        ///        &quot;ShoppingStatusName&quot;: &quot;Реализация&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_ShoppingStatus&quot;: 4,
        ///        &quot;ShoppingStatusName&quot;: &quot;Строительство&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    }
        ///].
        /// </summary>
        internal static string ShoppingCentersStatuses {
            get {
                return ResourceManager.GetString("ShoppingCentersStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;Id_Tenant&quot;: 1,
        ///        &quot;Name&quot;: &quot;AG Marine&quot;,
        ///        &quot;PhoneNumber&quot;: &quot;74955261453&quot;,
        ///        &quot;Address&quot;: &quot;Москва, Бабаевская улица д.16&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Tenant&quot;: 2,
        ///        &quot;Name&quot;: &quot;Art-elle&quot;,
        ///        &quot;PhoneNumber&quot;: &quot;74952505894&quot;,
        ///        &quot;Address&quot;: &quot;Санкт-Петербург, Амбарная улица д.25 корп.1&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Tenant&quot;: 3,
        ///        &quot;Name&quot;: &quot;Atlantis&quot;,
        ///        &quot;PhoneNumber&quot;: &quot;74954241165&quot;,
        ///        &quot;Add [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
    }
}
