//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUserControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFUserControls.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAA1wAAAOECAYAAAC1iDCGAACAAElEQVR42uzdCXxdZZ3/8b7mL9AW2qSUJl2AIsqugIOs4owLKioiqIgIhQI6KoqyCVaWguKCM6OgoKNsXdiRsq/SJmn2Zumatkn37Pvd93vO93/uuSkNUKBLcu+5536eeb0HxFKbNLn3fPt7nu8zJhKJCAAAAAAw8sbwSQAAAAAAAhcAAAAAELgAAAAAAAQuAAAAACBwAQAAAACBCwAAAABA4AIAAAAAAhcAAAAAELgAAAAAAAQuAAAAACBwAQAAAACBCwAAAABA4AIAAAAAAhcAAAAAELgAAAAAAAQuAAAAACBwAQAAAACBCwAAAABA4AIAAAAAAhcAAAAAELgAAAAAAAQuAAAAACBwAQAAAACBCwAAAABA4AIAAAAAAhcAAAAAELgAAAAAAAQuAAAAACBwAQAAAACBCwAAAABA4AIAAAAAAhcAAAAAELgAAAAAAAQuAAAAACBwAQAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
    }
}
