//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Resources.JsonResource", typeof(JsonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Id_Employee&quot;: 1,
        ///        &quot;Surname&quot;: &quot;Чашин&quot;,
        ///        &quot;Name&quot;: &quot;Елизар&quot;,
        ///        &quot;MIddlename&quot;: &quot;Михеевич&quot;,
        ///        &quot;Login&quot;: &quot;Elizor@gmail.com&quot;,
        ///        &quot;Password&quot;: &quot;XuS5gIyslrxC6avC/6rYua6iuwxBnN13sK+PBj5UiTc=&quot;,
        ///        &quot;Id_Role&quot;: 4,
        ///        &quot;PhoneNumber&quot;: &quot;71070628291&quot;,
        ///        &quot;Photo&quot;: null,
        ///        &quot;Gender&quot;: &quot;Муж&quot;,
        ///        &quot;RecordStatus&quot;: null
        ///    },
        ///    {
        ///        &quot;Id_Employee&quot;: 2,
        ///        &quot;Surname&quot;: &quot;Филенкова&quot;,
        ///        &quot;Name&quot;: &quot;Владлена&quot;,
        ///        &quot;MIddlename&quot;: &quot;Олеговна [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
    }
}
